name: Build and deploy static site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup a specific Nodejs environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.17'

      - name: Configure Gatsby (populates node_modules, takes forever)
        run: npm install

      - name: Build the static site directory tree
        run: npm run build

      - name: Deploy to production server
        env:
          WEBCI_KEY: ${{secrets.WEBCI_KEY}}
        run: |
          echo "$WEBCI_KEY" > /tmp/webcikey
          chmod 600 /tmp/webcikey
          rsync -avc --rsh="ssh -i /tmp/webcikey -o StrictHostKeyChecking=no" --delete ./public/ webci@trishproject.org:/home/webci/www
          rm /tmp/webcikey

